### ISSUE TITLE
Why use fixed point maths when it rounds badly even for a small number of decimal places?

### ISSUE THREAD

**Issue by Henry-E** [Bonfida/agnostic-orderbook#48]
Was just trying to work out why an ask order posted for 1 token (6 decimal places) was being posted for 0.999998 tokens instead and found that order was being rounded down because of the fixed point maths linked to the max_quote_qty.

Order / market details
- Tick_size: 0.1
- Side: Ask
- Limit price: 0.9
- max_base_qty: 1_000_000

The previous approach from v3 of using base lots and quote lots was confusing / messy but at least it wouldn't result in these kinds of rounding issues unless dealing with really large numbers that actually used up a lot of the available decimal places. This is only a single decimal place and it already has weird rounding issues. 

Maybe I'm just being petty but I would like to be able to make an order for selling 1 token and have it appear in the order book as 1 token.

**Comment by Henry-E** [comment]
Perhaps a higher FP number is needed for better precision. Mango uses i80f48, which gives the correct output

0.9 * 2^48 = 253327479039590.4
(1,000,000 * 253327479039590) / 2^48 = 900000.0 

Although obviously this comes with greater variable sizes and increased computational cost.

**Comment by ellttBen** [comment]
In the above example if you set `max_quote_qty` to `u64::MAX` then you should be able to get 1 token. This is precisely why orders can be specified either through `max_base_qty` or `max_quote_qty`.

We use FP32 because it represents enough precision of rmost use cases, and is fast and compact. Adding more decimal resolution to fix this kind of problem is the wrong answer to a questionable problem : there are more efficient ways of doing this (for instance if we want to have no rounding errors with 3 decimal places we can just store number as (floor(1000*n * 2**32)) instead of (n*2**32).

**Comment by ellttBen** [comment]
You would do it depending on whether you want to _spend_ a precise amount, or _buy_ a precise amount.

**Comment by Henry-E** [comment]
> In the above example if you set `max_quote_qty` to `u64::MAX` then you should be able to get 1 quote token. This is precisely why orders can be specified either through `max_base_qty` or `max_quote_qty`.

Having thought about it some more, I really don't like this solution. Making the program function such that the client places the user's true order quantity in one variable and u64::max in the other just seems like a recipe for disaster.
 
Another possible solution would be to calculate both the `max_base_qty` and `max_quote_qty` in the client, using the decimal value of the limit price. But this could also lead to maths issues down the line, since it's using the decimal limit price, rather than the FP32 limit price which has been modified to match the modulo of the tick size. So there's more potential maths weirdness when the modified FP32 limit price is being used to calculate order sizes and quantities in `order_book::new_order`.

The other solution presented involves multiplying all numbers you want a specific amount of decimal precision with by 10^n (n = number of decimal precision). Why add this extra level of awkwardness, this is how quote lots and base lots worked in serum v3. This solution just replicates that previous approach in addition to all of the FP32 stuff. 

You say FP32 presents enough precision for most use cases and I have the simplest possible example (a single decimal place) that demonstrates it lacks precision. The solutions required to get a round number just seem super awkward to implement and present a higher risk profile for things going wrong than more straightforward approaches.

Where I'm at is just that the program I'm working on needs to be modified to suit the problems raised in the issue and I don't have a clear path forward, so I'm feeling frustrated. I don't see a good, simple solution for getting round numbers and I can no longer trust the FP32 AOB code to not start outputting randomly imprecise numbers.

**Comment by Henry-E** [comment]
Thanks for the detailed response. I'm going to do my best to figure out the best solution given the great help you've provided!

From a UX standpoint I just think it looks bad if they order 1 token and the order goes through for 0.999998. That's mostly the perspective I was coming from.

Also the logic I was following, with only passing price and base quantity into my program's new order function, is that only `limit_price` and `max_base_quantity` of an order are actually stored on the order book. So, when it's a maker order `maker_quote_qty` has to be calculated using these values anyway. And this is the function I've been using to calculate `max_quote_qty`: `let max_quote_qty = fp32_mul(max_base_qty, limit_price);` Passing u64::max for `max_quote_qty` would result in a maker ask order being filled for 1 base token at 0.9 price but then you'd still end up with the rounding issues on the returned amount of quote currency, in this cause it's 0.899999 instead of just 0.9. But like, I guess there's no winning with the rounding stuff, it'll get you one way or the other!
 
 https://github.com/Bonfida/agnostic-orderbook/blob/87493c0e347ed6feccf1b17085a377d07a922437/program/src/orderbook.rs#L151

**Comment by ellttBen** [comment]
It's true that you can't get around these limitations for post-only or equivalent orders. If this is an issue for you can implement lots _outside_ the AOB, but still using the AOB, and abstract those away from the end-user. Since the AOB is, you know, agnostic, there's nothing stopping you from making the AOB reason in tenths or hundreths of tokens instead of the actual token itself. Then your calling program can perform the conversion just before calling. You can even perform this conversion on-chain since it's basically a multiplication.
This is a bit error-prone so you would need to careful, but it's really not too bad IMHO.
